#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

banner "Retire PrevCare Google prototype authority"

stage "Locate every legacy project"
say "Use the Google account that owns the prototype Sheet and Apps Script deployment."
open_url "https://script.google.com/home/my"
step "Search Apps Script projects for PrevCare and open every candidate in a separate tab."
step "Also open the original Google Sheet and check Extensions > Apps Script for a bound project."
warn "Do not paste project IDs, deployment URLs, credentials, or Student information into this wizard."
confirm "Have you located every standalone and Sheet-bound legacy project?" || exit 1

stage "Disable legacy deployments"
say "For each project, open Deploy > Manage deployments."
warn "Deleting a deployment is irreversible and immediately stops callers using its URL."
confirm "Are you authorized to disable these deployments now?" || exit 1
step "Archive or delete every deployment containing the old token or submission path."
step "If deletion is prohibited, replace it with google-apps-script/Code.gs and appsscript.json, set DATA_POLICY=synthetic-only, and remove EXECUTION_TOKEN."
confirm "Are all legacy deployments deleted, disabled, or replaced by the tombstone?" || exit 1

stage "Dispose of prototype Student data"
say "Follow the school's approved records process; this wizard does not decide retention or deletion authority."
confirm "Do you have a named school authority and approved disposition decision for these records?" || exit 1
step "Locate Submissions, StudentRegistry, AccessCodes, NurseRoster, and any copied prototype sheets."
warn "Do not delete records unless the named school authority has approved that disposition."
confirm "Has an authorized operator completed or formally scheduled disposition of every real Student record?" || exit 1

stage "Capture operator evidence"
if confirm "Did any legacy deployment require a tombstone replacement instead of deletion?"; then
  command -v curl >/dev/null 2>&1 || { warn "curl is required to verify the tombstone"; exit 1; }
  while true; do
    ask TOMBSTONE_URL "Paste one tombstone deployment URL (not a credential):"
    step "Checking the exact health, blocked POST, and blocked non-health GET responses."
    HEALTH_RESPONSE=$(curl --silent --show-error --fail "${TOMBSTONE_URL}?action=health")
    POST_RESPONSE=$(curl --silent --show-error --fail \
      --request POST \
      --header 'Content-Type: text/plain;charset=utf-8' \
      --data '{"action":"submitUpdate"}' \
      "$TOMBSTONE_URL")
    GET_RESPONSE=$(curl --silent --show-error --fail "${TOMBSTONE_URL}?action=studentSubmission")
    [[ "$HEALTH_RESPONSE" == '{"status":"ok","dataPolicy":"synthetic-only"}' ]] || {
      warn "health response did not match the synthetic-only tombstone"; exit 1;
    }
    [[ "$POST_RESPONSE" == '{"success":false,"error":"Prototype intake submissions are disabled"}' ]] || {
      warn "POST response did not reject intake submission"; exit 1;
    }
    [[ "$GET_RESPONSE" == '{"error":"Unknown action"}' ]] || {
      warn "non-health GET response was not rejected"; exit 1;
    }
    say "Tombstone boundary verified."
    confirm "Verify another tombstone deployment?" || break
  done
fi
ask OPERATOR_NAME "Operator name or approved identifier:"
ask CHANGE_REFERENCE "Non-sensitive change/disposition record reference:"
EVIDENCE_FILE="docs/security/prototype-retirement-evidence.md"
{
  printf '# Prototype Retirement Operator Evidence\n\n'
  printf -- '- Completed at: `%s`\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  printf -- '- Operator: `%s`\n' "$OPERATOR_NAME"
  printf -- '- Change/disposition reference: `%s`\n' "$CHANGE_REFERENCE"
  printf -- '- Legacy Apps Script deployments: deleted, disabled, or replaced by the no-scope tombstone.\n'
  printf -- '- Prototype Student records: disposition completed or formally scheduled under school authority.\n'
  printf -- '- Tombstone verification: health-only behavior confirmed where replacement was used.\n'
  printf -- '- Sensitive values recorded in this evidence: none.\n'
} > "$EVIDENCE_FILE"
say "Wrote $EVIDENCE_FILE. Review it and commit it with the approved change record."

finish
