#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

banner "Release-candidate acceptance evidence"

stage "Pin the exact release candidate"
say "Every outcome in this campaign must belong to one artifact digest, environment, schema, and School Configuration Release."
say "Do not mix rebuilt images, stale releases, or partial reruns. Start a new campaign instead."
step "Open /health/build on the staging origin and copy the 64-character artifactDigest and 40-character commit. Do not paste tokens."
ask ACCEPTANCE_ARTIFACT_DIGEST "Paste the artifact digest:"
ask ACCEPTANCE_COMMIT "Paste the commit SHA:"
ask ACCEPTANCE_ENVIRONMENT_HOST "Enter the staging host (example staging.up.railway.app):"
ask ACCEPTANCE_RELEASE_ID "Paste the active School Configuration Release uuid:"
ask ACCEPTANCE_IDENTITY_SET_ID "Paste the synthetic identity-set uuid:"
write_env ACCEPTANCE_ARTIFACT_DIGEST "$ACCEPTANCE_ARTIFACT_DIGEST"
write_env ACCEPTANCE_COMMIT "$ACCEPTANCE_COMMIT"
write_env ACCEPTANCE_ENVIRONMENT_HOST "$ACCEPTANCE_ENVIRONMENT_HOST"
write_env ACCEPTANCE_RELEASE_ID "$ACCEPTANCE_RELEASE_ID"
write_env ACCEPTANCE_IDENTITY_SET_ID "$ACCEPTANCE_IDENTITY_SET_ID"

stage "Native Edge and Safari observations"
say "Playwright Chromium and WebKit are automation proxies only. Native Edge and Safari remain pending until a human records them."
say "Do not paste invitation codes, sign-in codes, session cookies, or Intake answers."
step "On desktop and mobile viewports, walk the required journeys in native Edge if available."
if confirm "Did native Edge desktop and mobile pass without a journey-blocking defect?"; then
  ACCEPTANCE_EDGE_NATIVE=recorded_pass
else
  ACCEPTANCE_EDGE_NATIVE=pending
  warn "Native Edge stays pending. Chromium may be recorded separately as an automation proxy."
fi
step "On desktop and mobile viewports, walk the required journeys in native Safari if available."
if confirm "Did native Safari desktop and mobile pass without a journey-blocking defect?"; then
  ACCEPTANCE_SAFARI_NATIVE=recorded_pass
else
  ACCEPTANCE_SAFARI_NATIVE=pending
  warn "Native Safari stays pending. WebKit may be recorded separately as an automation proxy."
fi
write_env ACCEPTANCE_EDGE_NATIVE "$ACCEPTANCE_EDGE_NATIVE"
write_env ACCEPTANCE_SAFARI_NATIVE "$ACCEPTANCE_SAFARI_NATIVE"

stage "Five locale renditions"
say "Confirm en-US, es-US, pt-BR, fr-CA, and ht-HT render the required journeys. Record outcomes, not translated clinical content."
if confirm "Did all five locale renditions pass without a journey-blocking language or layout failure?"; then
  ACCEPTANCE_LOCALES=recorded_pass
else
  ACCEPTANCE_LOCALES=pending
  warn "Locale evidence stays pending until every supported rendition is recorded."
fi
write_env ACCEPTANCE_LOCALES "$ACCEPTANCE_LOCALES"

stage "School Nurse clinical and governance walkthrough"
say "A School Nurse must walk clinical reveal/clearing and authorize the domain outcome. The Technical Operator cannot substitute this."
step "Sign in as the School Nurse. Do not capture the password, TOTP secret, or revealed Intake answers."
step "Complete clinical reveal, then clear filters/selection and confirm the live announcement and print suppression."
step "Walk Records Governance, Production, Disposition, and Purge screens without exporting protected record contents into this wizard."
if confirm "Did the School Nurse complete clinical reveal, clearing, and governance journeys without a blocking defect?"; then
  ACCEPTANCE_SCHOOL_NURSE_JOURNEYS=recorded_pass
else
  ACCEPTANCE_SCHOOL_NURSE_JOURNEYS=pending
  warn "School Nurse journey evidence stays pending."
fi
write_env ACCEPTANCE_SCHOOL_NURSE_JOURNEYS "$ACCEPTANCE_SCHOOL_NURSE_JOURNEYS"

stage "School Nurse domain authorization"
say "Go/no-go is owned by the Technical Operator, but School Nurse acceptance is mandatory evidence."
ask ACCEPTANCE_SCHOOL_NURSE_STAFF_ID "Paste the School Nurse Staff Identity uuid (opaque id only):"
if confirm "Does the School Nurse authorize this release candidate for school acceptance?"; then
  ACCEPTANCE_SCHOOL_NURSE_STATUS=recorded
else
  ACCEPTANCE_SCHOOL_NURSE_STATUS=missing
  warn "Decision remains pending until School Nurse acceptance is recorded."
fi
write_env ACCEPTANCE_SCHOOL_NURSE_STAFF_ID "$ACCEPTANCE_SCHOOL_NURSE_STAFF_ID"
write_env ACCEPTANCE_SCHOOL_NURSE_STATUS "$ACCEPTANCE_SCHOOL_NURSE_STATUS"

stage "Record outcomes without secrets"
say "Use /operator or bun scripts/run-release-candidate-acceptance.ts to pin the campaign and export the non-sensitive bundle."
note "Provider backup, PITR, and alert routing still use scripts/record-operational-provider-evidence.sh. Those stay pending here until recorded."
note "Never write Intake answers, invitation or sign-in codes, session handles, or mailbox addresses into evidence."
step "If native Edge/Safari or School Nurse steps are still pending, leave them pending. Do not mark them passed."
pause "Human evidence notes are captured. Press Enter to finish."

finish
