/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/administration/school-workspaces': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['createSchoolWorkspace'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/administration/staff-identities': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['listStaffIdentities'];
    put?: never;
    post: operations['provisionStaffIdentity'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/staff/sign-in': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['startStaffSignIn'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/staff/sign-out': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['endStaffSession'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/staff/totp': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['completeStaffSignIn'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/clinical/review-directory': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['openClinicalDirectory'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/staff/session': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['readStaffSession'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health/live': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {string} */
              status: 'ok';
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health/ready': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {string} */
              status: 'ready';
            };
          };
        };
        /** @description Default Response */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {string} */
              status: 'not-ready';
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health/security': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {string} */
              status: 'ok';
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  createSchoolWorkspace: {
    parameters: {
      query?: never;
      header: {
        'x-prevcare-csrf': '1';
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          displayName: string;
          /** Format: uuid */
          operationId: string;
          /** Format: uuid */
          workspaceId: string;
        };
      };
    };
    responses: {
      /** @description Default Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            operationId: string;
            /** @enum {string} */
            outcome: 'created';
            /** Format: uuid */
            workspaceId: string;
          };
        };
      };
      /** @description Default Response */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': {
            code: string;
            status: number;
            title: string;
            type: string;
          };
        };
      };
      /** @description Default Response */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': {
            code: string;
            status: number;
            title: string;
            type: string;
          };
        };
      };
      /** @description Default Response */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': {
            code: string;
            status: number;
            title: string;
            type: string;
          };
        };
      };
      /** @description Default Response */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': {
            code: string;
            status: number;
            title: string;
            type: string;
          };
        };
      };
      /** @description Default Response */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': {
            code: string;
            status: number;
            title: string;
            type: string;
          };
        };
      };
      /** @description Default Response */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': {
            code: string;
            status: number;
            title: string;
            type: string;
          };
        };
      };
    };
  };
  listStaffIdentities: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            staffIdentities: {
              /** Format: date-time */
              createdAt: string;
              displayName: string;
              email: string;
              permissions: ('administrative' | 'clinical')[];
              /** Format: uuid */
              staffIdentityId: string;
              status: 'active' | 'disabled';
            }[];
          };
        };
      };
      /** @description Default Response */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': {
            code: string;
            status: number;
            title: string;
            type: string;
          };
        };
      };
      /** @description Default Response */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': {
            code: string;
            status: number;
            title: string;
            type: string;
          };
        };
      };
      /** @description Default Response */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': {
            code: string;
            status: number;
            title: string;
            type: string;
          };
        };
      };
    };
  };
  provisionStaffIdentity: {
    parameters: {
      query?: never;
      header: {
        'x-prevcare-csrf': '1';
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          displayName: string;
          /** Format: email */
          email: string;
          initialPassword: string;
          /** Format: uuid */
          operationId: string;
          permissions: ('administrative' | 'clinical')[];
          reason: string;
          schoolApprover: string;
          /** Format: uuid */
          staffIdentityId: string;
          /** Format: uuid */
          workspaceId: string;
        };
      };
    };
    responses: {
      /** @description Default Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            operationId: string;
            /** @enum {string} */
            outcome: 'provisioned';
            /** Format: uuid */
            staffIdentityId: string;
          };
        };
      };
      /** @description Default Response */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': {
            code: string;
            status: number;
            title: string;
            type: string;
          };
        };
      };
      /** @description Default Response */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': {
            code: string;
            status: number;
            title: string;
            type: string;
          };
        };
      };
      /** @description Default Response */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': {
            code: string;
            status: number;
            title: string;
            type: string;
          };
        };
      };
      /** @description Default Response */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': {
            code: string;
            status: number;
            title: string;
            type: string;
          };
        };
      };
      /** @description Default Response */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': {
            code: string;
            status: number;
            title: string;
            type: string;
          };
        };
      };
      /** @description Default Response */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': {
            code: string;
            status: number;
            title: string;
            type: string;
          };
        };
      };
    };
  };
  startStaffSignIn: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** Format: email */
          email: string;
          password: string;
        };
      };
    };
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: date-time */
            flowExpiresAt: string;
            flowHandle: string;
            otpauthUri?: string;
            stage: 'enroll' | 'totp';
          };
        };
      };
      /** @description Default Response */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': {
            code: string;
            status: number;
            title: string;
            type: string;
          };
        };
      };
      /** @description Default Response */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': {
            code: string;
            status: number;
            title: string;
            type: string;
          };
        };
      };
      /** @description Default Response */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': {
            code: string;
            status: number;
            title: string;
            type: string;
          };
        };
      };
      /** @description Default Response */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': {
            code: string;
            status: number;
            title: string;
            type: string;
          };
        };
      };
      /** @description Default Response */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': {
            code: string;
            status: number;
            title: string;
            type: string;
          };
        };
      };
    };
  };
  endStaffSession: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {string} */
            outcome: 'ended';
          };
        };
      };
      /** @description Default Response */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': {
            code: string;
            status: number;
            title: string;
            type: string;
          };
        };
      };
      /** @description Default Response */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': {
            code: string;
            status: number;
            title: string;
            type: string;
          };
        };
      };
      /** @description Default Response */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': {
            code: string;
            status: number;
            title: string;
            type: string;
          };
        };
      };
      /** @description Default Response */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': {
            code: string;
            status: number;
            title: string;
            type: string;
          };
        };
      };
    };
  };
  completeStaffSignIn: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          code: string;
          flowHandle: string;
        };
      };
    };
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {string} */
            outcome: 'authenticated';
          };
        };
      };
      /** @description Default Response */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': {
            code: string;
            status: number;
            title: string;
            type: string;
          };
        };
      };
      /** @description Default Response */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': {
            code: string;
            status: number;
            title: string;
            type: string;
          };
        };
      };
      /** @description Default Response */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': {
            code: string;
            status: number;
            title: string;
            type: string;
          };
        };
      };
      /** @description Default Response */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': {
            code: string;
            status: number;
            title: string;
            type: string;
          };
        };
      };
      /** @description Default Response */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': {
            code: string;
            status: number;
            title: string;
            type: string;
          };
        };
      };
    };
  };
  openClinicalDirectory: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            students: unknown[];
          };
        };
      };
      /** @description Default Response */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': {
            code: string;
            status: number;
            title: string;
            type: string;
          };
        };
      };
      /** @description Default Response */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': {
            code: string;
            status: number;
            title: string;
            type: string;
          };
        };
      };
      /** @description Default Response */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': {
            code: string;
            status: number;
            title: string;
            type: string;
          };
        };
      };
    };
  };
  readStaffSession: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: date-time */
            authenticatedAt: string;
            displayName: string;
            permissions: ('administrative' | 'clinical')[];
            /** Format: uuid */
            staffIdentityId: string;
            /** Format: uuid */
            workspaceId: string;
          };
        };
      };
      /** @description Default Response */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': {
            code: string;
            status: number;
            title: string;
            type: string;
          };
        };
      };
      /** @description Default Response */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': {
            code: string;
            status: number;
            title: string;
            type: string;
          };
        };
      };
    };
  };
}
